from __future__ import annotations

import os
from datetime import UTC, datetime
from uuid import uuid4

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import (
    BigInteger,
    Boolean,
    CHAR,
    DateTime,
    Engine,
    Integer,
    SmallInteger,
    Text,
    create_engine,
    inspect,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PostgreSQLUUID
from sqlalchemy.engine import make_url
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session


CORE_TABLES = {
    "boards",
    "posts",
    "post_metric_snapshots",
    "post_metric_snapshots_default",
    "collection_runs",
    "run_slots",
    "work_items",
    "security_quarantine",
}

COLUMN_CONTRACTS = {
    "boards": {
        "id": (("integer", None), False),
        "name": (("text", None), False),
        "kind": (("text", None), False),
    },
    "posts": {
        "board_id": (("integer", None), False),
        "post_id": (("bigint", None), False),
        "analysis_unit": (("text", None), False),
        "title": (("text", None), False),
        "published_at": (("timestamptz", None), False),
        "source_url": (("text", None), False),
        "is_notice": (("boolean", None), False),
        "is_ad": (("boolean", None), False),
        "current_category": (("text", None), True),
        "last_seen_at": (("timestamptz", None), False),
    },
    "post_metric_snapshots": {
        "board_id": (("integer", None), False),
        "post_id": (("bigint", None), False),
        "observed_at_slot_kst": (("timestamptz", None), False),
        "observed_at_actual": (("timestamptz", None), False),
        "views": (("bigint", None), False),
        "recommendations": (("integer", None), False),
        "comments": (("integer", None), False),
        "config_version": (("char", 64), False),
    },
    "collection_runs": {
        "id": (("uuid", None), False),
        "job_type": (("text", None), False),
        "scheduled_at_slot_kst": (("timestamptz", None), False),
        "status": (("text", None), False),
        "config_version": (("char", 64), False),
        "started_at": (("timestamptz", None), False),
        "finished_at": (("timestamptz", None), True),
        "diagnostics": (("jsonb", None), False),
    },
    "run_slots": {
        "job_type": (("text", None), False),
        "scheduled_at_slot_kst": (("timestamptz", None), False),
        "run_id": (("uuid", None), False),
    },
    "work_items": {
        "id": (("bigint", None), False),
        "task_key": (("text", None), False),
        "kind": (("text", None), False),
        "state": (("text", None), False),
        "priority": (("integer", None), False),
        "payload": (("jsonb", None), False),
        "payload_hash": (("char", 64), True),
        "attempts": (("integer", None), False),
        "available_at": (("timestamptz", None), False),
        "lease_owner": (("text", None), True),
        "lease_until": (("timestamptz", None), True),
        "last_error": (("text", None), True),
        "created_at": (("timestamptz", None), False),
        "updated_at": (("timestamptz", None), False),
    },
    "security_quarantine": {
        "id": (("uuid", None), False),
        "source_kind": (("text", None), False),
        "source_ref": (("text", None), False),
        "content_hash": (("char", 64), False),
        "findings": (("jsonb", None), False),
        "risk_score": (("integer", None), False),
        "quarantined_at": (("timestamptz", None), False),
        "review_state": (("text", None), False),
        "reviewer": (("text", None), True),
        "note": (("text", None), True),
        "released_at": (("timestamptz", None), True),
    },
}

PRIMARY_KEY_CONTRACTS = {
    "boards": ("id",),
    "posts": ("board_id", "post_id"),
    "post_metric_snapshots": ("board_id", "post_id", "observed_at_slot_kst"),
    "collection_runs": ("id",),
    "run_slots": ("job_type", "scheduled_at_slot_kst"),
    "work_items": ("id",),
    "security_quarantine": ("id",),
}

FOREIGN_KEY_CONTRACTS = {
    "boards": set(),
    "posts": {(("board_id",), "boards", ("id",))},
    "post_metric_snapshots": {(("board_id", "post_id"), "posts", ("board_id", "post_id"))},
    "collection_runs": set(),
    "run_slots": {(("run_id",), "collection_runs", ("id",))},
    "work_items": set(),
    "security_quarantine": set(),
}

UNIQUE_KEY_CONTRACTS = {
    "boards": set(),
    "posts": set(),
    "post_metric_snapshots": set(),
    "collection_runs": set(),
    "run_slots": set(),
    "work_items": {("task_key",)},
    "security_quarantine": {("source_kind", "source_ref", "content_hash")},
}

SERVER_DEFAULT_COLUMNS = {
    "boards": set(),
    "posts": {"is_notice", "is_ad", "last_seen_at"},
    "post_metric_snapshots": {"observed_at_actual"},
    "collection_runs": {"diagnostics"},
    "run_slots": set(),
    "work_items": {"id", "priority", "payload", "attempts", "created_at", "updated_at"},
    "security_quarantine": {"quarantined_at"},
}


def column_type_identity(column_type: object) -> tuple[str, int | None]:
    if isinstance(column_type, JSONB):
        return ("jsonb", None)
    if isinstance(column_type, PostgreSQLUUID):
        return ("uuid", None)
    if isinstance(column_type, DateTime):
        return ("timestamptz" if column_type.timezone else "timestamp", None)
    if isinstance(column_type, Boolean):
        return ("boolean", None)
    if isinstance(column_type, CHAR):
        return ("char", column_type.length)
    if isinstance(column_type, BigInteger):
        return ("bigint", None)
    if isinstance(column_type, SmallInteger):
        return ("smallint", None)
    if isinstance(column_type, Integer):
        return ("integer", None)
    if isinstance(column_type, Text):
        return ("text", None)
    raise AssertionError(f"unexpected reflected column type: {type(column_type).__name__}")


def test_core_table_identities_and_default_partition_exist(db_engine: Engine) -> None:
    table_names = set(inspect(db_engine).get_table_names())

    assert CORE_TABLES <= table_names
    with db_engine.connect() as connection:
        partition_bound = connection.execute(
            text(
                "SELECT pg_get_expr(child.relpartbound, child.oid) "
                "FROM pg_class AS child "
                "JOIN pg_namespace AS namespace ON namespace.oid = child.relnamespace "
                "WHERE namespace.nspname = current_schema() "
                "AND child.relname = 'post_metric_snapshots_default'"
            )
        ).scalar_one()
        partition_strategy, partition_columns = connection.execute(
            text(
                """
                SELECT partitioned.partstrat,
                       array_agg(attribute.attname ORDER BY partition_key.ordinality)
                FROM pg_catalog.pg_partitioned_table AS partitioned
                JOIN pg_catalog.pg_class AS parent ON parent.oid = partitioned.partrelid
                JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = parent.relnamespace
                CROSS JOIN LATERAL
                  unnest(partitioned.partattrs::smallint[]) WITH ORDINALITY
                  AS partition_key(attnum, ordinality)
                JOIN pg_catalog.pg_attribute AS attribute
                  ON attribute.attrelid = parent.oid
                 AND attribute.attnum = partition_key.attnum
                WHERE namespace.nspname = 'public'
                  AND parent.relname = 'post_metric_snapshots'
                GROUP BY partitioned.partstrat
                """
            )
        ).one()
    assert partition_bound == "DEFAULT"
    assert partition_strategy == "r"
    assert tuple(partition_columns) == ("observed_at_slot_kst",)


def test_catalog_column_types_and_nullability_match_exact_contract(db_engine: Engine) -> None:
    inspector = inspect(db_engine)

    for table_name, expected_columns in COLUMN_CONTRACTS.items():
        reflected_columns = {
            column["name"]: (column_type_identity(column["type"]), column["nullable"])
            for column in inspector.get_columns(table_name)
        }
        assert reflected_columns == expected_columns


def test_catalog_primary_foreign_and_unique_keys_match_exact_contract(
    db_engine: Engine,
) -> None:
    inspector = inspect(db_engine)

    for table_name in PRIMARY_KEY_CONTRACTS:
        primary_key = tuple(inspector.get_pk_constraint(table_name)["constrained_columns"])
        foreign_keys = {
            (
                tuple(foreign_key["constrained_columns"]),
                foreign_key["referred_table"],
                tuple(foreign_key["referred_columns"]),
            )
            for foreign_key in inspector.get_foreign_keys(table_name)
        }
        unique_keys = {
            tuple(unique_key["column_names"])
            for unique_key in inspector.get_unique_constraints(table_name)
        }

        assert primary_key == PRIMARY_KEY_CONTRACTS[table_name]
        assert foreign_keys == FOREIGN_KEY_CONTRACTS[table_name]
        assert unique_keys == UNIQUE_KEY_CONTRACTS[table_name]


def test_catalog_server_default_columns_match_exact_contract(db_engine: Engine) -> None:
    inspector = inspect(db_engine)

    for table_name, expected_columns in SERVER_DEFAULT_COLUMNS.items():
        defaulted_columns = {
            column["name"]
            for column in inspector.get_columns(table_name)
            if column["default"] is not None
        }
        assert defaulted_columns == expected_columns

    with db_engine.connect() as connection:
        work_item_id_sequence = connection.execute(
            text("SELECT pg_get_serial_sequence('public.work_items', 'id')")
        ).scalar_one()
    assert work_item_id_sequence is not None


def test_required_server_defaults_have_expected_semantics(db_session: Session) -> None:
    transaction_timestamp = db_session.execute(text("SELECT transaction_timestamp()")).scalar_one()
    db_session.execute(text("INSERT INTO boards (id, name, kind) VALUES (2294, 'warrior', 'job')"))
    post_defaults = db_session.execute(
        text(
            "INSERT INTO posts "
            "(board_id, post_id, analysis_unit, title, published_at, source_url) "
            "VALUES (2294, 457159, 'hero', 'title', now(), 'https://example.invalid/457159') "
            "RETURNING is_notice, is_ad, last_seen_at"
        )
    ).one()
    snapshot_defaults = db_session.execute(
        text(
            "INSERT INTO post_metric_snapshots "
            "(board_id, post_id, observed_at_slot_kst, views, recommendations, comments, "
            "config_version) "
            "VALUES (2294, 457159, now(), 1, 2, 3, repeat('a', 64)) "
            "RETURNING observed_at_actual"
        )
    ).one()
    collection_defaults = db_session.execute(
        text(
            "INSERT INTO collection_runs "
            "(id, job_type, scheduled_at_slot_kst, status, config_version, started_at) "
            "VALUES (:id, 'metadata', now(), 'running', repeat('b', 64), now()) "
            "RETURNING diagnostics"
        ),
        {"id": uuid4()},
    ).one()
    work_defaults = db_session.execute(
        text(
            "INSERT INTO work_items (task_key, kind, state, available_at) "
            "VALUES ('all-defaults:v1', 'detail_fetch', 'pending', now()) "
            "RETURNING id, priority, payload, attempts, created_at, updated_at"
        )
    ).one()

    assert post_defaults.is_notice is False
    assert post_defaults.is_ad is False
    assert post_defaults.last_seen_at == transaction_timestamp
    assert snapshot_defaults.observed_at_actual == transaction_timestamp
    assert collection_defaults.diagnostics == {}
    assert work_defaults.id > 0
    assert work_defaults.priority == 100
    assert work_defaults.payload == {}
    assert work_defaults.attempts == 0
    assert work_defaults.created_at == transaction_timestamp
    assert work_defaults.updated_at == transaction_timestamp


def test_snapshot_slot_is_idempotent(db_session: Session) -> None:
    db_session.execute(text("INSERT INTO boards (id, name, kind) VALUES (2294, '전사', 'job')"))
    db_session.execute(
        text(
            "INSERT INTO posts "
            "(board_id, post_id, analysis_unit, title, published_at, source_url) "
            "VALUES (2294, 457159, 'hero', '제목', now(), "
            "'https://example.invalid/457159')"
        )
    )
    statement = text(
        "INSERT INTO post_metric_snapshots "
        "(board_id, post_id, observed_at_slot_kst, views, recommendations, comments, "
        "config_version) "
        "VALUES (2294, 457159, '2026-07-14T06:20:00+09:00', 100, 2, 3, repeat('a', 64))"
    )
    db_session.execute(statement)
    db_session.commit()

    with pytest.raises(IntegrityError):
        db_session.execute(statement)
        db_session.commit()


def test_work_item_key_is_unique(db_session: Session) -> None:
    values = {
        "key": "detail:2294:457159:v1",
        "kind": "detail_fetch",
        "available_at": datetime.now(UTC),
    }
    statement = text(
        "INSERT INTO work_items (task_key, kind, state, available_at) "
        "VALUES (:key, :kind, 'pending', :available_at)"
    )
    db_session.execute(statement, values)
    db_session.commit()

    with pytest.raises(IntegrityError):
        db_session.execute(statement, values)
        db_session.commit()


@pytest.mark.parametrize("kind", ["", "general", "JOB"])
def test_board_kind_is_constrained(db_session: Session, kind: str) -> None:
    with pytest.raises(IntegrityError):
        db_session.execute(
            text("INSERT INTO boards (id, name, kind) VALUES (999, 'invalid', :kind)"),
            {"kind": kind},
        )
        db_session.commit()


@pytest.mark.parametrize("kind", ["job", "free", "info"])
def test_every_allowed_board_kind_is_accepted(db_session: Session, kind: str) -> None:
    saved_kind = db_session.execute(
        text("INSERT INTO boards (id, name, kind) VALUES (999, 'valid', :kind) RETURNING kind"),
        {"kind": kind},
    ).scalar_one()

    assert saved_kind == kind


@pytest.mark.parametrize("status", ["pending", "complete"])
def test_collection_run_status_is_constrained(db_session: Session, status: str) -> None:
    with pytest.raises(IntegrityError):
        db_session.execute(
            text(
                "INSERT INTO collection_runs "
                "(id, job_type, scheduled_at_slot_kst, status, config_version, started_at) "
                "VALUES (:id, 'metadata', now(), :status, repeat('a', 64), now())"
            ),
            {"id": uuid4(), "status": status},
        )
        db_session.commit()


@pytest.mark.parametrize("status", ["running", "succeeded", "partial", "failed"])
def test_every_allowed_collection_status_is_accepted(db_session: Session, status: str) -> None:
    saved_status = db_session.execute(
        text(
            "INSERT INTO collection_runs "
            "(id, job_type, scheduled_at_slot_kst, status, config_version, started_at) "
            "VALUES (:id, 'metadata', now(), :status, repeat('a', 64), now()) "
            "RETURNING status"
        ),
        {"id": uuid4(), "status": status},
    ).scalar_one()

    assert saved_status == status


@pytest.mark.parametrize("state", ["running", "complete"])
def test_work_item_state_is_constrained(db_session: Session, state: str) -> None:
    with pytest.raises(IntegrityError):
        db_session.execute(
            text(
                "INSERT INTO work_items (task_key, kind, state, available_at) "
                "VALUES (:key, 'detail_fetch', :state, now())"
            ),
            {"key": f"invalid:{state}", "state": state},
        )
        db_session.commit()


@pytest.mark.parametrize("state", ["pending", "leased", "succeeded", "retry", "dead"])
def test_every_allowed_work_state_is_accepted(db_session: Session, state: str) -> None:
    saved_state = db_session.execute(
        text(
            "INSERT INTO work_items (task_key, kind, state, available_at) "
            "VALUES (:key, 'detail_fetch', :state, now()) RETURNING state"
        ),
        {"key": f"valid:{state}", "state": state},
    ).scalar_one()

    assert saved_state == state


@pytest.mark.parametrize(
    ("column", "values"),
    [
        ("views", (-1, 0, 0)),
        ("recommendations", (0, -1, 0)),
        ("comments", (0, 0, -1)),
    ],
)
def test_snapshot_metrics_cannot_be_negative(
    db_session: Session, column: str, values: tuple[int, int, int]
) -> None:
    db_session.execute(text("INSERT INTO boards (id, name, kind) VALUES (2294, '전사', 'job')"))
    db_session.execute(
        text(
            "INSERT INTO posts "
            "(board_id, post_id, analysis_unit, title, published_at, source_url) "
            "VALUES (2294, 457159, 'hero', '제목', now(), "
            "'https://example.invalid/457159')"
        )
    )

    with pytest.raises(IntegrityError, match=column):
        db_session.execute(
            text(
                "INSERT INTO post_metric_snapshots "
                "(board_id, post_id, observed_at_slot_kst, views, recommendations, comments, "
                "config_version) VALUES "
                "(2294, 457159, now(), :views, :recommendations, :comments, repeat('a', 64))"
            ),
            dict(zip(("views", "recommendations", "comments"), values, strict=True)),
        )
        db_session.commit()


@pytest.mark.parametrize(
    ("views", "recommendations", "comments"),
    [(0, 1, 1), (1, 0, 1), (1, 1, 0)],
)
def test_each_snapshot_metric_accepts_zero_boundary(
    db_session: Session, views: int, recommendations: int, comments: int
) -> None:
    db_session.execute(text("INSERT INTO boards (id, name, kind) VALUES (2294, 'warrior', 'job')"))
    db_session.execute(
        text(
            "INSERT INTO posts "
            "(board_id, post_id, analysis_unit, title, published_at, source_url) "
            "VALUES (2294, 457159, 'hero', 'title', now(), "
            "'https://example.invalid/457159')"
        )
    )

    saved_metrics = db_session.execute(
        text(
            "INSERT INTO post_metric_snapshots "
            "(board_id, post_id, observed_at_slot_kst, views, recommendations, comments, "
            "config_version) VALUES "
            "(2294, 457159, now(), :views, :recommendations, :comments, repeat('a', 64)) "
            "RETURNING views, recommendations, comments"
        ),
        {"views": views, "recommendations": recommendations, "comments": comments},
    ).one()

    assert saved_metrics == (views, recommendations, comments)


def test_work_item_defaults_and_claim_index(db_session: Session) -> None:
    row = db_session.execute(
        text(
            "INSERT INTO work_items (task_key, kind, state, available_at) "
            "VALUES ('defaults:v1', 'detail_fetch', 'pending', now()) "
            "RETURNING priority, payload, attempts, created_at, updated_at"
        )
    ).one()

    assert row.priority == 100
    assert row.payload == {}
    assert row.attempts == 0
    assert row.created_at is not None
    assert row.updated_at is not None
    index = next(
        item
        for item in inspect(db_session.bind).get_indexes("work_items")
        if item["name"] == "work_items_claim_idx"
    )
    assert index["column_names"] == ["state", "priority", "available_at", "id"]


def test_migration_upgrade_downgrade_upgrade_round_trip(database_url: str) -> None:
    source_url = make_url(database_url)
    database_name = f"maple_monitor_roundtrip_{uuid4().hex}"
    admin_engine = create_engine(source_url.set(database="postgres"), isolation_level="AUTOCOMMIT")
    target_url = source_url.set(database=database_name)
    config = Config("alembic.ini")

    try:
        with admin_engine.connect() as connection:
            connection.exec_driver_sql(f'CREATE DATABASE "{database_name}"')
        os.environ["DATABASE_URL"] = target_url.render_as_string(hide_password=False)

        command.upgrade(config, "0001_core_collection")
        target_engine = create_engine(target_url)
        try:
            table_names = set(inspect(target_engine).get_table_names())
            assert CORE_TABLES - {"security_quarantine"} <= table_names
            assert "security_quarantine" not in table_names
        finally:
            target_engine.dispose()

        command.upgrade(config, "0002_security_quarantine")
        target_engine = create_engine(target_url)
        try:
            assert CORE_TABLES <= set(inspect(target_engine).get_table_names())
        finally:
            target_engine.dispose()

        command.downgrade(config, "0001_core_collection")
        target_engine = create_engine(target_url)
        try:
            table_names = set(inspect(target_engine).get_table_names())
            assert CORE_TABLES - {"security_quarantine"} <= table_names
            assert "security_quarantine" not in table_names
        finally:
            target_engine.dispose()

        command.upgrade(config, "head")
        target_engine = create_engine(target_url)
        try:
            assert CORE_TABLES <= set(inspect(target_engine).get_table_names())
        finally:
            target_engine.dispose()

        command.downgrade(config, "base")
        target_engine = create_engine(target_url)
        try:
            assert CORE_TABLES.isdisjoint(inspect(target_engine).get_table_names())
        finally:
            target_engine.dispose()

        command.upgrade(config, "head")
        target_engine = create_engine(target_url)
        try:
            assert CORE_TABLES <= set(inspect(target_engine).get_table_names())
        finally:
            target_engine.dispose()
    finally:
        os.environ["DATABASE_URL"] = database_url
        with admin_engine.connect() as connection:
            connection.exec_driver_sql(f'DROP DATABASE IF EXISTS "{database_name}" WITH (FORCE)')
        admin_engine.dispose()


def test_create_engine_from_env_connects_to_configured_database(
    database_url: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    from maple_monitor.db import create_engine_from_env

    monkeypatch.setenv("DATABASE_URL", database_url)
    engine = create_engine_from_env()
    try:
        with engine.connect() as connection:
            assert (
                connection.execute(text("SELECT current_database()")).scalar_one()
                == make_url(database_url).database
            )
        assert engine.pool.size() == 3
    finally:
        engine.dispose()


def test_create_engine_from_env_requires_database_url(monkeypatch: pytest.MonkeyPatch) -> None:
    from maple_monitor.db import create_engine_from_env

    monkeypatch.delenv("DATABASE_URL", raising=False)

    with pytest.raises(KeyError, match="DATABASE_URL"):
        create_engine_from_env()


def test_session_scope_commits_on_success(db_engine: Engine) -> None:
    from maple_monitor.db import session_scope

    board_id = 2_147_483_000
    with db_engine.begin() as connection:
        connection.execute(text("DELETE FROM boards WHERE id = :id"), {"id": board_id})
    try:
        with session_scope(db_engine) as session:
            session.execute(
                text("INSERT INTO boards (id, name, kind) VALUES (:id, 'commit', 'free')"),
                {"id": board_id},
            )

        with db_engine.connect() as connection:
            count = connection.execute(
                text("SELECT count(*) FROM boards WHERE id = :id"), {"id": board_id}
            ).scalar_one()
        assert count == 1
    finally:
        with db_engine.begin() as connection:
            connection.execute(text("DELETE FROM boards WHERE id = :id"), {"id": board_id})


def test_session_scope_rolls_back_on_error(db_engine: Engine) -> None:
    from maple_monitor.db import session_scope

    board_id = 2_147_483_001
    with db_engine.begin() as connection:
        connection.execute(text("DELETE FROM boards WHERE id = :id"), {"id": board_id})

    with pytest.raises(RuntimeError, match="force rollback"):
        with session_scope(db_engine) as session:
            session.execute(
                text("INSERT INTO boards (id, name, kind) VALUES (:id, 'rollback', 'free')"),
                {"id": board_id},
            )
            raise RuntimeError("force rollback")

    with db_engine.connect() as connection:
        count = connection.execute(
            text("SELECT count(*) FROM boards WHERE id = :id"), {"id": board_id}
        ).scalar_one()
    assert count == 0


def test_database_health_reports_ok_for_reachable_database(db_engine: Engine) -> None:
    from maple_monitor.ops.health import database_health

    assert database_health(db_engine) == {"database": "ok"}


def test_health_command_prints_success_json(database_url: str) -> None:
    import json

    from typer.testing import CliRunner

    from maple_monitor.cli import app

    result = CliRunner().invoke(app, ["health"], env={"DATABASE_URL": database_url})

    assert result.exit_code == 0, str(result.exception)
    assert json.loads(result.stdout) == {"database": "ok"}


def test_health_command_returns_nonzero_json_when_database_is_unreachable() -> None:
    import json

    from typer.testing import CliRunner

    from maple_monitor.cli import app

    unreachable_url = (
        "postgresql+psycopg://maple_monitor:maple_monitor@127.0.0.1:1/"
        "maple_monitor_test?connect_timeout=1"
    )
    result = CliRunner().invoke(app, ["health"], env={"DATABASE_URL": unreachable_url})

    assert result.exit_code == 1
    assert json.loads(result.stdout) == {"database": "error"}


def test_orm_metadata_describes_core_tables_and_snapshot_partition() -> None:
    from maple_monitor.models import Base, PostMetricSnapshot

    assert set(Base.metadata.tables) == CORE_TABLES - {"post_metric_snapshots_default"}
    assert (
        PostMetricSnapshot.__table__.dialect_options["postgresql"]["partition_by"]
        == "RANGE (observed_at_slot_kst)"
    )


def test_alembic_metadata_does_not_treat_runtime_partitions_as_schema_drift() -> None:
    command.check(Config("alembic.ini"))


def test_alembic_detects_server_default_drift(db_engine: Engine) -> None:
    with db_engine.begin() as connection:
        connection.execute(text("ALTER TABLE work_items ALTER COLUMN priority SET DEFAULT 101"))

    try:
        with pytest.raises(AutogenerateDiffsDetected) as drift:
            command.check(Config("alembic.ini"))
        differences = [
            difference
            for group in drift.value.diffs
            for difference in (group if isinstance(group, list) else [group])
        ]
        assert any(
            difference[0] == "modify_default"
            and difference[2] == "work_items"
            and difference[3] == "priority"
            for difference in differences
        )
    finally:
        with db_engine.begin() as connection:
            connection.execute(text("ALTER TABLE work_items ALTER COLUMN priority SET DEFAULT 100"))

    command.check(Config("alembic.ini"))


def test_alembic_drift_filter_excludes_only_real_snapshot_partitions(
    db_engine: Engine,
) -> None:
    archive_table = "post_metric_snapshots_archive"
    runtime_partition = "snapshot_metrics_999901_partition"
    with db_engine.begin() as connection:
        connection.execute(text(f'DROP TABLE IF EXISTS "{archive_table}"'))
        connection.execute(text(f'DROP TABLE IF EXISTS "{runtime_partition}"'))
        connection.execute(text(f'CREATE TABLE "{archive_table}" (id integer PRIMARY KEY)'))
        connection.execute(
            text(
                f'CREATE TABLE "{runtime_partition}" '
                "PARTITION OF post_metric_snapshots "
                "FOR VALUES FROM ('9999-01-01T00:00:00+09:00') "
                "TO ('9999-02-01T00:00:00+09:00')"
            )
        )

    try:
        with pytest.raises(AutogenerateDiffsDetected) as drift:
            command.check(Config("alembic.ini"))
        removed_tables = {
            difference[1].name
            for difference in drift.value.diffs
            if difference[0] == "remove_table"
        }
        assert archive_table in removed_tables
        assert runtime_partition not in removed_tables

        with db_engine.begin() as connection:
            connection.execute(text(f'DROP TABLE "{archive_table}"'))

        command.check(Config("alembic.ini"))
    finally:
        with db_engine.begin() as connection:
            connection.execute(text(f'DROP TABLE IF EXISTS "{archive_table}"'))
            connection.execute(text(f'DROP TABLE IF EXISTS "{runtime_partition}"'))


def test_alembic_partition_filter_uses_non_public_default_schema(
    database_url: str,
    db_engine: Engine,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    schema_name = f"alembic_partition_{uuid4().hex}"
    archive_table = "post_metric_snapshots_archive"
    runtime_partition = "snapshot_metrics_999902_partition"
    source_url = make_url(database_url)
    schema_url = source_url.update_query_dict({"options": f"-csearch_path={schema_name}"})
    config = Config("alembic.ini")

    with db_engine.begin() as connection:
        connection.execute(text(f'CREATE SCHEMA "{schema_name}"'))

    monkeypatch.setenv("DATABASE_URL", schema_url.render_as_string(hide_password=False))
    try:
        command.upgrade(config, "head")
        schema_engine = create_engine(schema_url)
        try:
            with schema_engine.begin() as connection:
                assert connection.dialect.default_schema_name == schema_name
                connection.execute(text(f'CREATE TABLE "{archive_table}" (id integer PRIMARY KEY)'))
                connection.execute(
                    text(
                        f'CREATE TABLE "{runtime_partition}" '
                        "PARTITION OF post_metric_snapshots "
                        "FOR VALUES FROM ('9999-02-01T00:00:00+09:00') "
                        "TO ('9999-03-01T00:00:00+09:00')"
                    )
                )

            with pytest.raises(AutogenerateDiffsDetected) as drift:
                command.check(config)
            removed_tables = {
                difference[1].name
                for difference in drift.value.diffs
                if difference[0] == "remove_table"
            }
            assert archive_table in removed_tables
            assert "post_metric_snapshots_default" not in removed_tables
            assert runtime_partition not in removed_tables

            with schema_engine.begin() as connection:
                connection.execute(text(f'DROP TABLE "{archive_table}"'))

            command.check(config)
        finally:
            schema_engine.dispose()
    finally:
        with db_engine.begin() as connection:
            connection.execute(text(f'DROP SCHEMA IF EXISTS "{schema_name}" CASCADE'))
